[package]
name = "staff"
version = "0.8.0"
edition = "2021"
license = "MIT"
description = "Music theory library with midi, notes, chords, scales, and more"
repository = "https://github.com/staff-rs/staff"
homepage = "https://staff-rs.github.io"

[features]
cli = ["anyhow", "clap", "render"]
render = ["dep:rusttype", "dep:svg", "dep:text-svg"]
serde = ["dep:serde"]
default = ["cli"]

[lib]
name = "staff"

[[bin]]
name = "staff"
required-features = ["cli"]

[dependencies]
num-traits = "0.2.14"
anyhow = { version = "1.0.61", optional = true }
thiserror = "1.0"
rusttype = { version = "0.9.3", optional = true }
svg = { version = "0.12.1", optional = true }
text-svg = { version = "0.1.2", optional = true }

[dependencies.clap]
version = "4.0.18"
features = ["derive"]
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true
